# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :build_sdk do
    sh("sh ./scripts/build.sh")
  end

  lane :tests do
    sh(" if [ ! -d #{project_directory} ]
    then
        mkdir #{project_directory}
    fi ")

    run_tests(clean: true,
            fail_build: false,
            scheme: "PagoApiClient",
            code_coverage: true,
            device: "iPhone 12",
            output_types: "html,junit",
            output_directory: "reports/")
  end
  
  #fastlane incrementVersion increment:<major|minor|patch>
  lane :incremenetVersion do |values|
    increment_version_number_in_xcodeproj(bump_type: values[:increment], target: "PagoApiClient")
  end
  
end
